### ISSUE TITLE
Can't open display.  Also - Gazebo 7.7 or 8.3 for qualifier?

### ISSUE THREAD

**Issue by stevegray954** [osrf/ariac-docker#18]
I just ran through the tutorial on the `master` branch and saw that Gazebo 7.7 is being used.  I saw @dhood mentioned in PR#17 that 7.7 will be used until logging issues in 8.3 are fixed.  Any idea if this will happen before the March 2018 qualifier?

Also, should it be opening a display?  
```
[Err] [RenderEngine.cc:730] Can't open display: 
[Wrn] [RenderEngine.cc:97] Unable to create X window. Rendering will be disabled
```

I saw in PR #6 that GPU support was removed, but I'm not sure if it should be opening an X window anyway. I see the TODO about re-enabling nvidia support in [run_container.bash](https://github.com/osrf/ariac-docker/blob/master/ariac-server/run_container.bash)

**Comment by dhood** [comment]
It shouldn't be opening a display, you can ignore the message. I'll update the readme to clarify this, thanks for pointing it out!

I will get back to you about the ETA of gazebo 8.

**Comment by stevegray954** [comment]
Good to know, thanks for the speedy reply! Does this mean I should switch back to Gazebo 7.7?  The install instructions for `ariac2` include installing Gazebo 8.3.

Is it possible to open the display (without having the nvidia support)?  And/or any plans to re-enable nvidia support?

**Comment by dhood** [comment]
You can keep working with gazebo8 on your host machine (the core functionality of the simulator shouldn't be affected by the change between 7 and 8); the docker image will be updated to use gazebo8 within the week.

An external display isn't supported at the moment (the images purposefully block external clients for the purpose of preventing unpermitted access), and there aren't plans to re-enable nvidia support. We recommend replaying the gazebo state logs instead.

Depending on how comfortable you are with Docker, you can rebuild the Docker images commenting [these lines](https://github.com/osrf/ariac-docker/blob/9d27b54707112f32dee64c068cdf89c967bcbf62/ariac-server/ariac-server/ariac_entrypoint.sh#L16..L17) to allow external gzclients (e.g. with `GAZEBO_IP=172.23.1.167 GAZEBO_MASTER_URI=http://172.18.0.22:11345 gzclient --verbose` on the host). You might run into issues with a gazebo8 client connecting to a gazebo7 server though, in which case you'd have to rebuild ariac from source using gazebo7... The option is there, but as I mentioned it's unsupported, so if you go down that road I won't be able to give you extra help I'm afraid.

By the way (since you're working on this right now), please keep https://github.com/osrf/ariac-docker/issues/19 in mind

**Comment by stevegray954** [comment]
Right now I can't play back the log at all with Gazebo 8.3 on my host machine. Here's the ticket I filed in ariac issues.
https://bitbucket.org/osrf/ariac/issues/95/state-log-from-automated-evaluation-wont

**Comment by dhood** [comment]
Latest `ariac2-server` Docker image (ariac2.0.6) is using gazebo8.4.
